name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'
      - name: Instalar dependencias y compilar Angular
        run: |
          npm install
          npm run build --prod
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_CLIFF_00A8B530F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Se usa para integraciones en GitHub (por ejemplo, comentarios en pull requests)
          action: "upload"
          ###### Configuraciones del repositorio y build ######
          # Verifica que estos valores se ajusten a la estructura y ubicación de tu aplicación.
          app_location: "/"            # Ruta base del código fuente de la aplicación
          api_location: ""             # Ruta de la API (opcional)
          output_location: "dist/serverless-example/browser"  # Ubicación de los archivos compilados que_
